services:
  api:
    build: .
    environment:
      PORT: 8000
      APP_MODULE: "main:app"
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "8001:8001"
    restart: always
    depends_on:
      - postgres
    command: ["/start-reload.sh"]  # auto reload for development

  jaegertracing:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  postgres:
    image: "postgres:12"
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    restart: always